### ISSUE TITLE
Flake8 extensions seem to be buggy

### ISSUE THREAD

**Issue by hvelarde** [plone/plone.recipe.codeanalysis#172]
I have found problems with at least 2 extensions: flake8-coding and flake8-quotes. This is probably an issue of Falke8 itself but I want to leave record of this problem here.

These are the extensions I'm using on [my buildout configuration](https://github.com/collective/collective.googlenews/blob/master/buildout.cfg#L21:L25):

```
[code-analysis]
recipe = plone.recipe.codeanalysis
...
flake8-extensions =
    flake8-blind-except
    flake8-coding
    flake8-debugger
    flake8-quotes
flake8-ignore = E501
```

As you can see code analysis seems to be ok: https://travis-ci.org/collective/collective.googlenews/jobs/94003673#L1166

Even as I have issues on at least 2 files:

* this one, for instance, does no have the magic coding comment: https://github.com/collective/collective.googlenews/blob/master/collective/googlenews/Extensions/__init__.py
* this one, is using double quotes on strings: https://github.com/collective/collective.googlenews/blob/master/collective/googlenews/controlpanel.py#L13:L15

**Comment by gforcada** [comment]
@hvelarde flake8-coding latest version allows you to ignore empty ``__init__.py`` files, so that you don't need to add the magic coding comment, maybe you have some buildouts with a newer/older version and that's the bugginess you see?

As for the second error I see that you fixed it, no idea why it failed, but that's the whole point of using flake8 extensions, that p.r.codeanalysis is not the one to blame but the extensions themselves. Smaller projects which are easier to fix/update/release etc (or fork if they are not responsive/want to take different approaches).

So please, report any error you see on the upstream projects.

I'm closing as this is nothing we can fix on p.r.codeanalysis.
