### ISSUE TITLE
remove default parameters

### ISSUE THREAD

**Issue by iham** [plone/plone.recipe.codeanalysis#221]
flake can use setup.cfg*, tox.ini or .flake for configuring parameters like "max-line-length"
editors like sublime text, eclipse, vs code, etc can use this files too.
*setup.cfg seems to be the most common as this file is widely used (isort, manifest, distutils, ...)

sadly, this file is ignored when parameters are set during script-calls (see bin/code-analysis-flake8)
even if they are not set, default values will be added to code-analysis-flake8 and the setup.cfg can't be used

in order to not duplicate code, it would be nice to only use the setup.cfg and skip flake8 configuration in buildout completely.

**Comment by MrTango** [comment]
I just realized that, if we use this in a project buildout, we don't have a setup.cfg, so we will need a tox.ini or a .flake8 file. I would vote for using the tox.ini, as we will use this more and more in packages and buildout anyway. Because of that, we will add a tox file by default to addon's created by bobtemplates.plone/plonecli. As this is already merged and released, I'll close this issue.
