### ISSUE TITLE
Refactor the code to use an OO approach

### ISSUE THREAD

**Issue by ramiroluz** [plone/plone.recipe.codeanalysis#62]
I intend to rewrite the code in an Object Oriented style, making it more easy to maintain. 

My plan is to keep the functions API so it will not break code that might be using the functions.

**Comment by saily** [comment]
I just rebased the branch `issue62` and try to improve it.

**Comment by gforcada** [comment]
@saily thanks for working on this!

I haven't take a look at the code since long ago, but it would be great if we can do a step by step migration of the code. A complete rewrite usually kills development peace on the way... So if it's feasible, please send pull requests as soon as the amount of refactoring can be released alone without breaking everything else :)

**Comment by saily** [comment]
Pull opened, please review - was a lot of work to do ;-)
