### ISSUE TITLE
Check manifest file for completeness

### ISSUE THREAD

**Issue by gforcada** [plone/plone.recipe.codeanalysis#69]
And the last tool to integrate for today (maybe):

https://pypi.python.org/pypi/check-manifest

**Comment by saily** [comment]
@hvelarde sorry, but you're wrong. You can't ship a general all matching `MANIFEST.in` file. 
`check-manifest` validates your distributed package with the source checkout, to ensure all files are included into the distributed package. I'd really like `check-manifest` and if we decide to implement this i would take this task.

So since we just talked about this topic, can you @jensens also provide feedback on this?

**Comment by aclark4life** [comment]
I can provide feedback: always use a MANIFEST.in and always check it with [check-manifest](https://pypi.python.org/pypi/check-manifest) :smile: 

(I'm not sure how there can be any debate around verifying package integrity. Maybe you can debate how to automate it… oh, and I agree there are no all-encompassing rules that can suffice. MANIFEST.in will vary from package to package.)

**Comment by jensens** [comment]
+1 for check manifest. as usal the option can be switched off i assume? (for those who do not like it in their projects)

**Comment by saily** [comment]
as @aclark4life told us, we should not allow to turn it off - right ;-)

**Comment by jensens** [comment]
+1 to not allow it in plone core

**Comment by gforcada** [comment]
so now that we have an agreement, anyone doing the pull request? :)

**Comment by saily** [comment]
Yes, i will do this. Butt currently i'm also working on #62 in parallel so this might take one or two weekends ;-)

**Comment by hvelarde** [comment]
first of all, [you don't need a MANIFEST.in file at all](http://stackoverflow.com/a/24727824/644075); if we are including it is because our ``setup.py`` scripts suck.

From [Python 2.7 documentation](https://docs.python.org/2/distutils/sourcedist.html#specifying-the-files-to-distribute):

> ## 4.1. Specifying the files to distribute

> If you don’t supply an explicit list of files (or instructions on how to generate one), the sdist command puts a minimal default set into the source distribution:

> * all Python source files implied by the ``py_modules`` and ``packages`` options
> * all C source files mentioned in the ``ext_modules`` or ``libraries`` options
> * scripts identified by the ``scripts`` option See [Installing Scripts](https://docs.python.org/2/distutils/setupscript.html#distutils-installing-scripts).
> * anything that looks like a test script: ``test/test*.py`` (currently, the Distutils don’t do anything with test scripts except include them in source distributions, but in the future there will be a standard for testing Python module distributions)
> * ``README.txt`` (or ``README``), ``setup.py`` (or whatever you called your setup script), and ``setup.cfg``
> * all files that matches the package_data metadata. See [Installing Package Data](https://docs.python.org/2/distutils/setupscript.html#distutils-installing-package-data).
> * all files that matches the data_files metadata. See [Installing Additional Files](https://docs.python.org/2/distutils/setupscript.html#distutils-additional-files).

having said that, and after having read your comments, I'm not against of including this option now, but I think we have to take care of other equally important things like having the right trove classifiers and the metadata filled in Plone core packages, and take special care when naming a release.

it really bugs me that Plone core packages doesn't clearly define which Plone versions they are intended to work on and there have been, in the past, bug fixes releases that break compatibility with an specific version of Plone.

**Comment by aclark4life** [comment]
@hvelarde You're referencing the distutils documentation, which is not particularly relevant here unfortunately.

**Comment by aclark4life** [comment]
@hvelarde Also no one ever said you "need" it. I can't speaking for anyone else, but I'm saying **always include it** for reasons to lengthy to discuss here.

**Comment by hvelarde** [comment]
@aclark4life from the [setuptools documentation](https://pythonhosted.org/setuptools/setuptools.html):

> # Building and Distributing Packages with Setuptools

> Setuptools is a collection of enhancements to the Python distutils (for Python 2.6 and up) that allow developers to more easily build and distribute Python packages, especially ones that have dependencies on other packages.

> [...]

> Feature Highlights:

> [...]

> * **Automatically include all relevant files in your source distributions, without needing to create a MANIFEST.in file, and without having to force regeneration of the MANIFEST file when your source tree changes.**

if your point doesn't fit 140 chars, then it can't be tweeted.

we need tools that check trove classifiers and metadata more than this.

**Comment by aclark4life** [comment]
@hvelarde the setuptools documentation is not particularly relevant here, unfortunately. Also

- For trove and metadata checks, use ``pyroma``.

- ``MANIFEST.in`` should always be included despite **the documented requirement of "without needing to create a MANIFEST.in".**

- ``check-manifest`` should always be used to check ``MANIFEST.in``

**Comment by hvelarde** [comment]
sorry, @aclark4life, but this conversation is going nowhere because you are not providing arguments but opinions; if that is the case, then I stay with my opinion and I will always use a standard vanilla MANIFEST.in with 3 or 4 lines... problem solved...

thanks for the tip on pyroma, unfortunately seems there's no way to enforce certain classifiers with it anyway.

**Comment by aclark4life** [comment]
@hvelarde You don't have to apologize and you can always do as you like! I think you misunderstand me, I'm not "providing opinions" I'm telling you what to do. Why you should do it is quite inconsequential (you don't really want to know why, I suspect. It has to do with years and years of dealing with various packaging woes and is not possible to explain in a sentence or two). Why you should do what I say is also inconsequential. You either trust me or you don't I don't blame you if you don't :smile: Good luck!

**Comment by aclark4life** [comment]
If pressed for a rational thought, I'd say this: let's do everything we can to reduce confusion, be consistent and verify integrity across multiple packages. Although not strictly required, using ``MANIFEST.in`` and checking rules with ``check-manifest`` is one way to do that. Not doing it is possible but not my preference as it invites confusion, inconsistency and lack of integrity.

**Comment by do3cc** [comment]
Using Manifest files are more robust than letting setuptools deduce required files from the package. setuptools does so by analysing the vcs information. For git it needs a plugin last time I checked. When you forget about the plugin, it can happen that you create a broken egg. This has happened in the past multiple times for me. I am sure that others have had the problem too. 
This package is about reducing possible failure modes and not adding a manifest and relying optional packages without any warning if given package is missing is a failure mode.
@hvelarde Is this a good argument? @saily

**Comment by gforcada** [comment]
@hvelarde I'm looking forward for your pull requests on https://github.com/plone/jenkins.plone.org to add checks for all the missing troves and so on. If you just provide the shell/python script that checks for one package alone that's also fine as well, we can take care of the jenkins job and putting it in production.

@saily thanks for stepping up!

**Comment by saily** [comment]
just to close this discussion, while digging through the old issues here, i found a bug #27 opened by the person which is currently fighting against this manifest check :wink:

**Comment by hvelarde** [comment]
@saily yes, I was the original proponent of this feature and that was 6 months before I realized that it was not so useful at all, at least for me; and I'm not fighting against anything; did you realized that I agree with you 3 days ago?

@aclark4life thanks for enlighten me; now every time I have a doubt I will look for you, not because you're good on explaining, but because you are the one who really knows: "I'm telling you what to do… dude"

:beers:

**Comment by tisto** [comment]
Being able to change opinions is a sign of strength in my opinion, not something that we should hold against anyone.

BTW: I would like to hear @mauritsvanrees opinion on that issue.

**Comment by aclark4life** [comment]
@hvelarde Sorry, what I mean is: "please trust me this is the right thing to do" and I don't say that a lot because I hate when people say that to me. Thank you @do3cc for accurately expressing my reasoning when I couldn't. :smile: (You may not realize it, @hvelarde but quoting distutils and setuptools documentation to someone who has lived packaging issues for at least 5 years is incredibly insulting. I'm sure you didn't mean it to be, but it was. And I have no interest in explaining *why* it's insulting or why the documentation is not relevant here. As you said, I'm offering a single opinion among many, and I should be able to do that and have an opinion without folks throwing moot documents back in my face. :smile:) :beers:

**Comment by hvelarde** [comment]
@do3cc yes, is a good one.

@gforcada I'm thinking on it but is not going to be easy, we need first to populate current ``setup.py`` scripts for all the packages that make up Plone.

**Comment by aclark4life** [comment]
@hvelarde And if you really want an explanation, surely you can politely ask for one instead of pasting in documentation. (As if to say "see? that's all there is to it! It's written down right here!") :hammer:

**Comment by jensens** [comment]
So coming back from theories to my current practical work: 
At least w/o ``MANIFEST.in`` our usal ``README.rst`` and ``CHANGES.rst`` would not be included by default. So I need it. And if a ``MANIFEST.in`` is existent and its broken, the whole egg is a brown-bag release. I had this in past more than one time. So big +1 for such a check.
If theres a better and simpler way: Please show me. All I found (vcs-plugins) are not.

**Comment by gforcada** [comment]
@hvelarde I would do in incrementally: first check that Plone and Zope trovers are there and report about it, if there are Plone trovers but not for any specific version, report about it, the license trover would be nice as well, and programming language python and specifically python 2.7 would be great.

So basically a script that runs on a full checkout environment (so we have access to setup.py of all modules) and reports how many of them are missing trovers.

Once we have that in jenkins it's a perfect first task to be done for a newcomer.

**Comment by gforcada** [comment]
@hvelarde and a bit more on the topic, checking that there is a MANIFEST.in would be extra super nice :)

**Comment by hvelarde** [comment]
it's funny that some of you seem not to be actually reading what I wrote:

* I never have been against having a ``MANIFEST.in`` file; I think we always must validate that file exist
* I was arguing about the need of checking the contents of that file using ``check-manifest`` because, as I mentioned at the very beginning of this endless and boring thread, a typical ``MANIFEST.in`` in all of my projects requires only 4 lines (after adding a previously missing ``global-exclude *.pyc``)

and that's all folks; I'm not reopening this discussion: just do what you have to do, according on what was decided by all of us.

@gforcada ``check-manifest``  will do the thing: just use the ``--update`` option, that will create the file in case it is missing.

**Comment by aclark4life** [comment]
@hvelarde Fair enough! It seemed like you were referencing distutils and setuptools documentation to dispute the need for MANIFEST.in and subsequently ``check-manifest``. My apologies if that was not the case. And what I was trying to convey from "point one" was: "we don't need to debate this; it should be easy enough to include both MANIFEST.in and subsequently ``check-manifest`` and thereby avoid the debate entirely. I am sorry, too, if I underestimated the importance of having an open dialogue about it. :smile:

**Comment by mauritsvanrees** [comment]
My point of view, since I was mentioned: yes, include check-manifest. I am using it, with the hook it has into zest.releaser (just like pyroma has BTW). It hooks into the release part (create tag, create sdist and upload to pypi). Running it on its own in Jenkins seems helpful. It is an easy way to avoid brown bag releases that miss files, especially when you start renaming txt files to rst, or moving stuff from a docs directory to the main directory. I was very happy with it last week after I did something like that.

check-manifest checks if the files under version control are all included in the source distribution. Some packages may not need a MANIFEST.in, most will. Some may have a working setup.py that does all of this properly for them and that is up to date. I ultimately do not care whether files are included because a of MANIFEST.in or a setup.py, as long as they are included. Personally I am happy with including a MANIFEST.in, and it looks like we all agree on that after all.

I would be against using setuptools-git. That package should be fine, but there have been problems with setuptools-bzr in combination with various bzr versions. And setuptools-svn or setuptools-subversion or the builtin svn support in distutils/setuptools suffered from subversion updates, causing brown bag releases. So I like to not depend on such a package. Having a check-manifest job in Jenkins would be protecting us against some developer in the future making releases while not having setuptools-git, for a package where we were unknowingly relying on it.

BTW, to avoid false positives by check-manifest, compaining about missing files that I actually do not want to include, I often add a setup.cfg, something like this:

[check-manifest]
ignore =
    bootstrap.py
    buildout.cfg

We could debate whether we want to include such files in our Plone core sdists after all. In some cases it can be be useful to see what a working buildout config and bootstrap (which version) for a certain version of a package would be. But mostly it is not interesting.

**Comment by saily** [comment]
I did a lot of tests with check-manifest and already opened a pull for basic integration. A thing i'd love to implement for `coredev` buildout would be:

    [code-analysis]
    ...
    check-manifest = True
    check-manifest-directory = ${buildout:develop}

This would basically work, but with current architecture of `check-manifest` we need to bootstrap every develop package first, to provide setuptools to check-manifest. If i don't do this i get following error (i'm working in a virtualenv in coredev directory):

    Traceback (most recent call last):
      File "setup.py", line 2, in <module>
        from setuptools import find_packages
    ImportError: No module named setuptools

Any ideas how we could solve this without bootstrapping each package?

**Comment by gforcada** [comment]
@saily actually that shouldn't be much of a problem as instead of running from buildout.coredev itself (or at least not only), my first and foremost usage would it be in the so-called single package jobs. i.e. jenkins jobs which only checkout a single package (p.a.discussion, p.a.contenttypes...) where bootstraping will be already part of the process.

Instead of doing global QA from within buildout.coredev it makes much more sense to do it on a per package basis. This way it's easier to keep it sane and granular.

And I would say that it should be the same for every project, at der Freitag I'm aiming for something like this actually as well.
